In [90]:
import pandas as pd
import numpy as np

In [91]:
data=pd.read_csv('orders.csv',na_values=['Not Available', 'unknown'])
df=pd.DataFrame(data)

In [92]:
df.head(10)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [93]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [94]:
df.columns

Index(['Order Id', 'Order Date', 'Ship Mode', 'Segment', 'Country', 'City',
       'State', 'Postal Code', 'Region', 'Category', 'Sub Category',
       'Product Id', 'cost price', 'List Price', 'Quantity',
       'Discount Percent'],
      dtype='object')

In [95]:
df.columns=df.columns.str.lower()

In [96]:
df.columns

Index(['order id', 'order date', 'ship mode', 'segment', 'country', 'city',
       'state', 'postal code', 'region', 'category', 'sub category',
       'product id', 'cost price', 'list price', 'quantity',
       'discount percent'],
      dtype='object')

In [97]:
df.columns=df.columns.str.replace(' ','_')

In [98]:
df.head(10)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

# Derive the new columns discount , sale price and profit

In [99]:
df['discount']=df['list_price']*df['discount_percent']*.01
df.head()
df['sale_price']=df['list_price']-df['discount']

In [100]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0

# Profit

In [101]:
df['Profit']=df['sale_price']-df['cost_price']

In [102]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

# Convert order date from object data type to datetime

In [103]:
df['order_date']=pd.to_datetime(df['order_date'],format="%Y-%m-%d")

In [104]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
Profit                     float64
dtype: object

# drop cost price,list price, and discount percent column

In [105]:
df.drop(columns=['cost_price','discount_percent','list_price'],inplace=True)

In [106]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [107]:
df.to_csv(r"C:/Users/Aditya/OneDrive/Desktop/retail_order_DA(py+sql)/orders_m.csv", index=False)

# Load this data into SQL server using replace option

In [108]:
import mysql.connector

In [109]:
conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='root',
    database='orders_and_retail'
)

cur = conn.cursor()

In [110]:
query=""" select * from orders_m """

cur.execute(query)

data=cur.fetchall()

df = pd.DataFrame(data, columns=[col[0] for col in cur.description])
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,Profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2346,2347,2022-12-27,Standard Class,Consumer,United States,San Antonio,Texas,78207,Central,Office Supplies,Binders,OFF-BI-10004141,2,0.0,0.0,0.0
2347,2348,2022-09-09,Standard Class,Consumer,United States,San Antonio,Texas,78207,Central,Furniture,Tables,FUR-TA-10004619,5,28.0,532.0,12.0
2348,2349,2022-09-14,Same Day,Corporate,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10004187,6,0.4,9.6,-0.4
2349,2350,2023-04-02,Same Day,Corporate,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10000632,2,3.5,66.5,6.5
2350,2351,2023-12-16,Same Day,Corporate,United States,Los Angeles,California,90032,West,Office Supplies,Paper,OFF-PA-10003724,2,0.5,9.5,-0.5

# find the higest revenue generating product

In [111]:
query=""" select product_id,sum(sale_price) as sales 
    from orders_m 
    group by product_id
    order by sales desc
    limit 10"""

cur.execute(query)

data=cur.fetchall()

df = pd.DataFrame(data, columns=[col[0] for col in cur.description])
df

        product_id    sales
0  TEC-MA-10000822  13770.0
1  TEC-MA-10004125   7840.0
2  OFF-BI-10003527   7148.9
3  FUR-BO-10004834   5267.6
4  OFF-BI-10004995   5242.9
5  TEC-MA-10000488   5236.8
6  OFF-SU-10002881   5223.4
7  TEC-PH-10004165   4724.7
8  TEC-MA-10003979   4655.0
9  FUR-TA-10003473   4390.9

# find top 5 highest selling products in each region

In [79]:
query=""" select region,product_id,sum(sale_price) as sales 
    from orders_m 
    group by region,product_id
    order by region,sales desc"""

cur.execute(query)

data=cur.fetchall()

df = pd.DataFrame(data, columns=[col[0] for col in cur.description])
df

      region       product_id    sales
0    Central  TEC-MA-10000822  10801.8
1    Central  FUR-CH-10004063   2542.0
2    Central  TEC-MA-10003353   2444.4
3    Central  FUR-CH-10000454   1891.5
4    Central  FUR-CH-10004287   1670.4
..       ...              ...      ...
279     West  OFF-AR-10002053      9.5
280     West  OFF-BI-10001634      9.5
281     West  OFF-FA-10002988      0.0
282     West  OFF-BI-10003274      0.0
283     West  OFF-AP-10003622      0.0

[284 rows x 3 columns]

In [112]:
query=""" with cte as(select region,product_id,sum(sale_price) as sales 
    from orders_m 
    group by region,product_id)
    select * from( select * ,
    row_number() over (partition by region order by sales desc) as rn
    from cte) A
    where rn<=5"""

cur.execute(query)

data=cur.fetchall()

df = pd.DataFrame(data, columns=[col[0] for col in cur.description])
df

     region       product_id    sales  rn
0   Central  TEC-MA-10000822  13770.0   1
1   Central  TEC-PH-10004165   2985.4   2
2   Central  FUR-CH-10001854   2669.5   3
3   Central  TEC-PH-10001363   2630.4   4
4   Central  FUR-CH-10004063   2542.0   5
5      East  OFF-SU-10002881   5223.4   1
6      East  TEC-MA-10003979   4655.0   2
7      East  OFF-BI-10004995   4185.6   3
8      East  TEC-MA-10002927   3910.2   4
9      East  TEC-MA-10000488   3840.0   5
10    South  TEC-MA-10004125   7840.0   1
11    South  OFF-BI-10003527   6159.5   2
12    South  TEC-PH-10001530   3191.6   3
13    South  TEC-MA-10000010   2948.8   4
14    South  OFF-BI-10003925   2665.6   5
15     West  FUR-TA-10003473   3795.7   1
16     West  TEC-AC-10003832   3502.7   2
17     West  TEC-CO-10001766   3055.5   3
18     West  FUR-TA-10004256   2872.9   4
19     West  TEC-CO-10003236   2850.0   5

# find month over month growth comparison for 2022 and 2023 sales eg: jan 2022 vs jan 2023

In [125]:
query=""" with cte as(select year(order_date) as order_year,
            month(order_date) as order_month ,
            sum(sale_price) as sales
        from orders_m
        group by  year(order_date),month(order_date)) 
       select order_month,
           sum(case when order_year=2022 then sales else 0 end) as sales_2022,
           sum(case when order_year=2023 then sales else 0 end) as sales_2023
        from cte
        group by order_month
        order by order_month"""
cur.execute(query)

data=cur.fetchall()

df = pd.DataFrame(data, columns=[col[0] for col in cur.description])
df

    order_month  sales_2022  sales_2023
0             1     25309.7     11994.3
1             2     15892.8     36469.1
2             3     13445.0     21753.5
3             4     16458.9     27072.4
4             5     18546.7     19997.9
5             6     27501.4     12610.5
6             7     15704.3     19784.7
7             8     18682.9     21385.0
8             9     14979.9     19366.8
9            10     33389.9     28195.3
10           11     16406.3     18646.6
11           12     21808.5     28363.8

# for each category which month has highest sales

In [144]:
query=""" with cte as (select category,
        format(order_date,'yyyyMM') as month,
        sum(sale_price) as total_sales
    from orders_m 
    group by category, format(order_date,'yyyyMM'))
    select * from(
    select *,
    row_number() over (partition by category order by total_sales desc)as rn
    from cte) a
    where rn=1
    """

cur.execute(query)

data=cur.fetchall()

df = pd.DataFrame(data, columns=[col[0] for col in cur.description])
df

          category  month  total_sales  rn
0        Furniture  2,023      89877.0   1
1  Office Supplies  2,023      79232.9   1
2       Technology  2,023      96530.0   1

# which subcategory has highest growth by profit in 2023 compate to 2022

In [160]:
query="""with cte as(select sub_category,year(order_date) as order_year,
            sum(sale_price) as sales
        from orders_m
        group by  year(order_date),sub_category) 
       ,cte2 as 
       (select sub_category,
           sum(case when order_year=2022 then sales else 0 end) as sales_2022,
           sum(case when order_year=2023 then sales else 0 end) as sales_2023
        from cte
        group by sub_category)
        select * ,
        (sales_2023-sales_2022)*100/sales_2022 as Growth
        from cte2
        order by growth desc
        limit 1
    """

cur.execute(query)

data=cur.fetchall()

df = pd.DataFrame(data, columns=[col[0] for col in cur.description])
df

  sub_category  sales_2022  sales_2023      growth
0     Supplies      1904.7      5920.6  210.841602